#pyproject.toml
[project]
requires-python = ">=3.7"
[build-system]
# Minimum requirements for the build system to execute.
requires = ['setuptools>=45.0', 'cython>=0.29', 'oldest-supported-numpy', 'mpi4py']