name: Build and deploy

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_ENVIRONMENT: >
            PATH=$PATH:/usr/lib64/mpich/bin/ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/mpich/lib CC=mpicc MPICC=mpicc
          CIBW_BEFORE_ALL: >
            yum install mpich-devel lapack-devel metis-devel -y &&
            cp Makefile.in.info Makefile.in &&
            make TACS_DIR=${PWD} METIS_LIB=-lmetis
          CIBW_TEST_EXTRAS: "testing"
          CIBW_BEFORE_TEST: >
            export PATH=$PATH:/usr/lib64/mpich/bin/ &&
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/mpich/lib &&
            export CC=mpicc &&
            export MPICC=mpicc
          CIBW_TEST_COMMAND: echo $LD_LIBRARY_PATH && testflo {project}/tests/
          CIBW_BUILD_VERBOSITY: 3

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
